README.md
src/components/Comment.svelte
src/components/Comments.svelte
src/components/MobileMenu.svelte
src/components/Nav.svelte
src/components/Newsletter.svelte
src/routes/[slug].svelte
src/routes/__layout.svelte
src/routes/about.svx
src/routes/blog.svelte
src/routes/index.svelte

closes #16 and improves the design on mobile

styling for mobile

---

README.md
src/app.html
src/lib/content.js

closes #25  for now (too lazy to do static tweets as [it is a lot of work](https://github.com/lfades/static-tweet/tree/main/lib))

add supportembeds

---

src/routes/api/blog/[slug].json.js
src/routes/api/listContent.json.js
src/routes/api/rss.xml.js

Change `s-max-age` to `s-maxage` as documented in [Cache-Control](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#s-maxage).

Update Cache-Control headers

---

src/lib/content.js

https://stackoverflow.com/questions/65347907/remove-unused-javascript-base-js-youtube-iframe-api

improve youtube embed

---

src/routes/[slug].svelte

See https://twitter.com/hdorodev/status/1545150871457128450 :)

fix: ensure proper canonicals in posts' pages

---

package-lock.json
package.json
vite.config.js

See build error with svelte-kit's latest update: https://app.netlify.com/sites/swyxkit/deploys/62d006f103ab40000806a6fc

Fix svelte-kit build is no longer available

---

package-lock.json
package.json
src/routes/+error.svelte
src/routes/[slug]/+page.js
src/routes/api/blog/[slug].json/+server.js
src/routes/blog/+page.svelte

closes https://github.com/sw-yx/swyxkit/issues/90

fix ideas filter and 404 page

---

src/lib/content.js

Numeric slug currently throws an exception.

handle numeric slug

---

package-lock.json
package.json

to solve https://github.com/sveltejs/kit/issues/6592

attempt upgrade of adapter auto again

---

package-lock.json
package.json
src/lib/content.js
src/routes/+page.svelte

Handles the edge cases which were failing before we added the dependency for slugify.

no dependency slugify

---

package-lock.json
package.json
src/components/IndexCard.svelte
src/lib/content.js
src/routes/+layout.svelte
src/routes/+page.js
src/routes/+page.svelte
src/routes/[slug]/+page.svelte
src/routes/blog/+page.svelte
src/tailwind.css
tailwind.config.cjs

https://ryanmulligan.dev/blog/layout-breakouts/

add layout breakouts

---

README.md
src/routes/about/+page.svx

Just a few adjustments to the text in the `about` page I noticed while looking at the live demo. :)
@sw-yx Now that I think about it, should this be updated to match the repo's README?

chore(about): small text adjustments

---

README.md
netlify.toml
package-lock.json
package.json
src/routes/[slug]/+page.svelte
src/routes/api/blog/[slug].json/+server.js
svelte.config.js

as described in https://github.com/pngwn/MDsveX/issues/484

try to fix PrismJS Rendering bug

---

README.md
package-lock.json
package.json
src/lib/content.js
src/routes/api/listContent.json/+server.js
src/routes/rss.xml/+server.js

make RSS rich html instead of markdown

---

README.md
package-lock.json
package.json
src/components/CommentsAndReactions.story.svelte
src/components/FeatureCard.story.svelte
src/components/MiscComponents.story.svelte
src/components/_sampledata.js

in the upgrade to sveltekit 1.0, i had to disable histoire because it had not caught up to vite 4. now it has.

re-add histoire back for vite4

---

src/routes/[slug]/+page.svelte

turns out it was pretty simple lol 
closes #93

fix diff highlighting

---

package-lock.json
package.json
src/components/IndexCard.svelte
src/lib/content.js
src/lib/siteConfig.js
src/routes/[slug]/+page.svelte
src/routes/blog/+page.svelte
src/routes/blog/MostPopular.svelte

initially i disabled the Categories functionality out of the box because i was worried that people would be scared off with the additional complexity
but now i think it should be exposed to nudge people to write more things.

add index page categories

---

package.json

My machine crashed after I ran `npm run dev` 😆. Fix so that it does not run infinitely

fix: npm run dev

---

src/routes/[slug]/+page.svelte
src/routes/[slug]/loadUtterances.js
src/routes/blog/+page.svelte
src/routes/blog/fuzzySearch.js

lazyload search and make async for stable UX at scale

---

README.md

...to preserve markdown formatting for parser

change of frontmatter example for tags to an array

---

package.json

Add missing dependency to package.json, which was added only to lock file

Add missing dependency to package.json
